server:
    port: 8443
    ssl:
        key-store: ./store/keystore.jks
        key-store-password: qwert123
        key-alias: localhost
        key-password: qwert123
        enabled: true
spring:
    security:
        user:  
            name: Admin
            password: admin